name: WordPress Deployment Workflow

on:
  push:
    branches:
      - main # Customize to the branch you want to trigger this workflow on

jobs:
  build:
    runs-on: ubuntu-latest # You can specify the runner environment here

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP and MySQL
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4 # Customize to your PHP version
        extensions: mbstring, mysqli, pdo, pdo_mysql

    - name: Install Composer and Node.js
      uses: shivammathur/setup-php@v2
      with:
        tools: composer, nodejs # Install Composer and Node.js

    - name: Install WordPress Dependencies
      run: |
        composer install
        npm install

    - name: Build WordPress Assets
      run: npm run build # If you're using a build process for assets

    - name: Set up MySQL Database
      run: |
        mysql -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -h ${{ secrets.DB_HOST }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }}"

    - name: Configure WordPress
      run: |
        cp wp-config-sample.php wp-config.php
        sed -i "s/database_name_here/${{ secrets.DB_NAME }}/g" wp-config.php
        sed -i "s/username_here/${{ secrets.DB_USER }}/g" wp-config.php
        sed -i "s/password_here/${{ secrets.DB_PASSWORD }}/g" wp-config.php

    - name: Deploy to Production
      run: |
        # Add your deployment commands here (e.g., rsync, FTP, etc.)
        # Example: rsync -avz --exclude='.git' ./ user@yourserver:/path/to/your/wordpress

    - name: Clear Cache and Update Permalinks
      run: |
        # Add commands to clear cache or update permalinks here if needed

    - name: Deploy Completed
      run: |
        # Add any post-deployment steps here if needed
